### ISSUE TITLE
Installation Error on Ubuntu 16.04, 64bit

### ISSUE THREAD

**Issue by 040840308** [raineorshine/solgraph#31]
I tried to install solgraph through "npm install --save -g solgraph" on ubuntu 16.04. However, I failed with some errors:
root@ubuntu:# npm install --save -g solgraph
/usr/local/bin/solgraph -> /usr/local/lib/node_modules/solgraph/solgraph.js

> solgraph@0.3.1 postinstall /usr/local/lib/node_modules/solgraph
> npm run build

> solgraph@0.3.1 build /usr/local/lib/node_modules/solgraph
> babel -d dist src

Error: [BABEL] /usr/local/lib/node_modules/solgraph/src/bin.js: The pipeline operator requires a proposal set. You must pass 'pipelineProposal' option to @babel/preset-stage-1 (While processing: "/usr/local/lib/node_modules/solgraph/node_modules/@babel/preset-stage-1/lib/index.js")
    at _default (/usr/local/lib/node_modules/solgraph/node_modules/@babel/preset-stage-1/lib/index.js:116:11)
    at /usr/local/lib/node_modules/solgraph/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/usr/local/lib/node_modules/solgraph/node_modules/@babel/core/lib/config/full.js:157:14)
    at cachedFunction (/usr/local/lib/node_modules/solgraph/node_modules/@babel/core/lib/config/caching.js:32:19)
    at loadPresetDescriptor (/usr/local/lib/node_modules/solgraph/node_modules/@babel/core/lib/config/full.js:227:63)
    at config.presets.map.descriptor (/usr/local/lib/node_modules/solgraph/node_modules/@babel/core/lib/config/full.js:72:19)
    at Array.map (<anonymous>)
    at recurseDescriptors (/usr/local/lib/node_modules/solgraph/node_modules/@babel/core/lib/config/full.js:70:38)
    at loadFullConfig (/usr/local/lib/node_modules/solgraph/node_modules/@babel/core/lib/config/full.js:100:6)
    at process.nextTick (/usr/local/lib/node_modules/solgraph/node_modules/@babel/core/lib/transform-file.js:48:33)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! solgraph@0.3.1 build: `babel -d dist src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the solgraph@0.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/solgraph/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! solgraph@0.3.1 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the solgraph@0.3.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-06T17_44_46_341Z-debug.log

**Comment by raineorshine** [comment]
Hmmm the build is passing on https://travis-ci.org/raineorshine/solgraph

@jpantunes Another babel issue. Any ideas?

**Comment by jpantunes** [comment]
Submitted new PR. 
Basic local test passes, but I suggest further testing is needed.

**Comment by shishangx** [comment]
i have the same problem in windows 10.

**Comment by slakov** [comment]
Same here - Ubuntu 18.04

**Comment by raineorshine** [comment]
`"pipelineProposal": "minimal"` added and published in `v0.3.2`. Please try again and report here. If you still cannot install, additional help would be appreciated to reproduce.

**Comment by slakov** [comment]
Resolved for me. Many thanks!

**Comment by shishangx** [comment]
resolved too.
